### PR TITLE
Boris ivanov

### PR DESCRIPTION
**Pull request by BorisThereIs**
Hi, I think my implementation meets the requirements. Please review and let me know in case I should fix something. I did several tests and [Github Actions reported that we are good](https://github.com/1712n/twitter-bot-challenge/actions/runs/3943614816/jobs/6748644875)

### CODE REVIEW

**Comment by darknessest** [comment]
@BorisThereIs, great work on that aggregation, unfortunately your submission produces invalid tweets, please look into that.

**Comment by BorisThereIs** [comment]
> @BorisThereIs, great work on that aggregation, unfortunately, your submission produces invalid tweets, please look into that.

Hi @darknessest, thanks for your comment. Regarding your notice about "invalid tweets", to be honest, I'm not sure what does that mean. I appreciate any additional explanation from your side in order to fix/change my implementation.

My bot produces one tweet for one selected pair per one run. If I got right, the aggregation process meets your expectation, as per your words "great work on that aggregation". Which means my pipeline returned a correct pair_to_post.

I tested my bot several times locally before I submited PR and one time via gh actions. I attached a couple of screenshots of a result of the [last run](https://github.com/1712n/twitter-bot-challenge/actions/runs/3943614816/jobs/6748644875) through gh actions: a new tweet was published in thread and related record was inserted into posts_db.

mcbot_screenshot_1

mcbot_screenshot_2

**Comment by darknessest** [comment]
> Hi @darknessest, thanks for your comment. Regarding your notice about "invalid tweets", to be honest, I'm not sure what does that mean. I appreciate any additional explanation from your side in order to fix/change my implementation.

Sorry, sure, I should've started with more concrete examples, you can check the last three runs of your submission from the [e13cbc6](https://github.com/1712n/twitter-bot-challenge/pull/26/commits/e13cbc64250a8d3206e48f984904a31bc49c441e) commit, and you can have a look at the logs [here](https://github.com/1712n/twitter-bot-challenge/actions/runs/3943614816/jobs/6749427030)

**Comment by BorisThereIs** [comment]
> > Hi @darknessest, thanks for your comment. Regarding your notice about "invalid tweets", to be honest, I'm not sure what does that mean. I appreciate any additional explanation from your side in order to fix/change my implementation.
> 
> Sorry, sure, I should've started with more concrete examples, you can check the last three runs of your submission from the [e13cbc6](https://github.com/1712n/twitter-bot-challenge/pull/26/commits/e13cbc64250a8d3206e48f984904a31bc49c441e) commit, and you can have a look at the logs [here](https://github.com/1712n/twitter-bot-challenge/actions/runs/3943614816/jobs/6749427030)

Hi @darknessest , since ~2000_years_later_meme.jpg~ your last comment I eventually accomplished a stable run with correct results. I eliminated bugs and add some features.
You can check [recent gh actions run](https://github.com/1712n/twitter-bot-challenge/actions/runs/3954508082/jobs/6771917053). Now logs look nicer.

Recently posted tweets: [1](https://twitter.com/CryptoCapBot/status/1615885826868772865) , [2](https://twitter.com/CryptoCapBot/status/1615877755370934275) , [3](https://twitter.com/CryptoCapBot/status/1615867073552420866)

**Please check/review one more time.**

**Pull request closed without merging**
