### PR TITLE
Timujin

### PR DESCRIPTION
**Pull request by timujin**
Hello!
This is my submission. I hope everything is correct.

### CODE REVIEW

**Comment by darknessest** [comment]
@timujin, it seems like you are halfway to meeting the requirements. Consider the case when your code is run not once an hour, but more frequently, will there be a variety of pairs? You can refer to [step 3](https://github.com/1712n/twitter-bot-challenge/issues/8) in the algorithm's description

**Comment by timujin** [comment]
I changed the logic of choosing the pair to post. I hope the responses would be more varied now.

**Comment by timujin** [comment]
@sofiasedlova tagging you, too

**Comment by darknessest** [comment]
It still seems like your code can't be run several times in a short period of time. In other aspects, it looks good.

**Comment by timujin** [comment]
@darknessest @sofiasedlova Try it now, I changed the logic of pair choice.

**Review by darknessest — APPROVED** [review]
@timujin, great work, you've met the technical requirements of the challenge. 
If you decide to improve something in your submission it will be taken into account when we'll be deciding on a winner of the challenge.

**Pull request closed without merging**
