### PR TITLE
Eg-mart

### PR DESCRIPTION
**Pull request by eg-mart**
Hi! I think I've met all of the requirements.

### CODE REVIEW

**Comment by darknessest** [comment]
Great work, @eg-mart, your solution looks perfect.
Just one minor thing, could you fix the negative zero in your final tweets (see this [example](https://twitter.com/CryptoCapBot/status/1616564811977920512?s=20) from [this run](https://github.com/1712n/twitter-bot-challenge/actions/runs/3956085863/jobs/6809046062))

**Comment by eg-mart** [comment]
I think I've fixed the negative zero, but I've noticed another problem: there seems to be a lot of documents in ohlcv with pair `LTC-USD` and market `okx` that were posted at the same time, and as they differ only by their volume and market_id, my code breaks on them (see [this tweet](https://twitter.com/CryptoCapBot/status/1616603381304537089?s=20&t=SFxb3YSwebBNVE8N1ihCsg). What is my bot supposed to do in this situation?

**Comment by darknessest** [comment]
> I think I've fixed the negative zero, but I've noticed another problem: there seems to be a lot of documents in ohlcv with pair `LTC-USD` and market `okx` that were posted at the same time, and as they differ only by their volume and market_id, my code breaks on them (see [this tweet](https://twitter.com/CryptoCapBot/status/1616603381304537089?s=20&t=SFxb3YSwebBNVE8N1ihCsg)). What is my bot supposed to do in this situation?

That's up to you to decide, how to handle malformed metrics, you can always just skip the pair

**Review by darknessest — APPROVED** [review]
Thank you @eg-mart, for your work, you've met the technical requirements of our challenge.

**Comment by eg-mart** [comment]
Thank you!

**Review by sofiasedlova — APPROVED** [review]

**Pull request merged**
