### PR TITLE
Rodri

### PR DESCRIPTION
**Pull request by MagicRodri**
Hi,
I'm done with my first implementation of the bot. Could you review and test it out, and let me know if there is something I've missed ?

### CODE REVIEW

**Comment by darknessest** [comment]
@MagicRodri, great work!
There's just one detail: could you tweak the pair selection logic (which pair to tweet about)? Please refer to the third step in the [algorithm description](https://github.com/1712n/twitter-bot-challenge/issues/8#issue-1500824045).

**Comment by MagicRodri** [comment]
> @MagicRodri, great work! There's just one detail: could you tweak the pair selection logic (which pair to tweet about)? Please refer to the third step in the [algorithm description](https://github.com/1712n/twitter-bot-challenge/issues/8#issue-1500824045)

Ok, I'll check it. But is there any reason to continue now that there is already an approved pull request?

**Comment by MagicRodri** [comment]
> @MagicRodri, great work! There's just one detail: could you tweak the pair selection logic (which pair to tweet about)? Please refer to the third step in the [algorithm description](https://github.com/1712n/twitter-bot-challenge/issues/8#issue-1500824045).

I've modified the pair choice logic.

**Comment by darknessest** [comment]
@MagicRodri looks good, we probably should've explicitly said that pairs in a tweet should be sorted in descending order. 
Could you sort the pairs?

**Comment by MagicRodri** [comment]
Ok, corrected it.

**Review by darknessest — APPROVED** [review]
Perfect, I think at this point you've met all the requirements

**Pull request closed without merging**
